### ISSUE TITLE
APPS DO NOT WORK

### ISSUE THREAD

**Issue by RedNotSus** [55gms/55GMS#29]
they pull you to undefined - prob an issue w/ cookies or the new system pls fix i dont know @22yeets22 
urgent issue

**Comment by RedNotSus** [comment]
@22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22 @22yeets22

**Comment by RedNotSus** [comment]
silly mistake

**Comment by 22yeets22** [comment]
all ur fault
