### ISSUE TITLE
internal server error?

### ISSUE THREAD

**Issue by 22yeets22** [55gms/55GMS#44]
check the server logs maybe
![Screenshot 2024-04-18 8 43 41 AM](https://github.com/55gms/55GMS/assets/132288501/8bea160d-62f2-4763-a423-15d9841aaa2d)
@RedNotSus

**Comment by RedNotSus** [comment]
was downtime since I had to upgrade server, was maxing out cpu and ram and network so I upgraded

**Comment by 22yeets22** [comment]
when

**Comment by 22yeets22** [comment]
still occuring

**Comment by RedNotSus** [comment]
duplacate
