### ISSUE TITLE
Remove navbar on the home page

### ISSUE THREAD

**Issue by 22yeets22** [55gms/55GMS#49]
The home page is commonly viewed by almost all of the viewers of our site, but the navbar grabs the attention of the user before the "dashboard button." The dashboard has a lot of code written in it, and I believe removing the navbar of the home page will increase our site's cohesiveness.

**Comment by RedNotSus** [comment]
nah navbar speeds up the process of getting to what a user wants

**Comment by 22yeets22** [comment]
ok i knew it @RedNotSus 
working on a pull request

**Comment by RedNotSus** [comment]
no we have the navbar stay on home page

**Comment by RedNotSus** [comment]
navbar = good

**Comment by RedNotSus** [comment]
dashboard is just motd and qotd

**Comment by 22yeets22** [comment]
> YEAH YOURE RIGHT LETS REMOVE THE NAVBAR!!!

why are you changing your mind. if they click the button they see MORE FEATURES

**Comment by 22yeets22** [comment]
ooohhhhhhh

**Comment by 22yeets22** [comment]
nobody notice and i spent time on the dashboard.

**Comment by RedNotSus** [comment]
they notice

**Comment by RedNotSus** [comment]
you just dont see analytics
