### ISSUE TITLE
55gms site v6.wiki keeps disconnecting from cloudfare

### ISSUE THREAD

**Issue by bahabryra** [55gms/55GMS#52]
when you open cloudfare it shows cloudfare:
If I were to leave my home forever with only 1 suitcase and it is XXL I would take all the devices that are solar-powered and if there are any that are not I would bring a solar-powered charger. Then I would bring a food generator that creates food from the air.
This website v6.wiki is currently offline. [Cloudflare's Always Online™](https://www.cloudflare.com/always-online/) shows a snapshot of this web page from the [Internet Archive's Wayback Machine](https://archive.org/web/). To check for the live version, click Refresh.

if It is just 1 page it shows:
This website (ex:) v6.wiki/g (/Ex:) is currently offline. [Cloudflare's Always Online™](https://www.cloudflare.com/always-online/) shows a snapshot of this web page from the [Internet Archive's Wayback Machine](https://archive.org/web/). To check for the live version, click Refresh.

**Comment by bahabryra** [comment]
@RedNotSus 
@22yeets22

**Comment by RedNotSus** [comment]
clear cache

**Comment by RedNotSus** [comment]
fixed

**Comment by bahabryra** [comment]
![Screenshot 2024-04-24 2 57 59 PM](https://github.com/55gms/55GMS/assets/160906216/1225cab7-9fa7-4260-bad2-da27f9145377)
![Screenshot 2024-04-24 2 57 34 PM](https://github.com/55gms/55GMS/assets/160906216/f47d984d-aad6-4a54-b4d9-1fb5162fb239)
![Screenshot 2024-04-24 2 57 30 PM](https://github.com/55gms/55GMS/assets/160906216/6e110616-352b-42b1-80ce-2f73927ed16e)
![Screenshot 2024-04-24 2 57 26 PM](https://github.com/55gms/55GMS/assets/160906216/acd9f769-9611-48e1-8386-d9b504d7dd61)
![Screenshot 2024-04-24 2 57 20 PM](https://github.com/55gms/55GMS/assets/160906216/7f2f7d99-f98b-4bea-9895-2fabbc07143c)
![Screenshot 2024-04-24 2 57 13 PM](https://github.com/55gms/55GMS/assets/160906216/2a3a2e6d-78ee-461c-a49d-53078d2830db)
I did clear but games  still broken

**Comment by bahabryra** [comment]
@RedNotSus 
@22yeets22

**Comment by RedNotSus** [comment]
not like that for me

**Comment by bahabryra** [comment]
did you check v6.wiki
