### ISSUE TITLE
v6.wiki question

### ISSUE THREAD

**Issue by bahabryra** [55gms/55GMS#79]
could you make a couple of domains using v6.wiki

example
coding.v6.wiki
math.v6.wiki
ect.

**Comment by bahabryra** [comment]
???

**Comment by RedNotSus** [comment]
why not just v6.wiki

**Comment by bahabryra** [comment]
it was because it would unblock it for me but they just made it not possible






On Monday, December 16, 2024 at 09:57:55 PM CST, rednotsus ***@***.***> wrote: 







why not just v6.wiki

**Comment by RedNotSus** [comment]
https://prod.v25.dev/

**Comment by RedNotSus** [comment]
all good try http://docs.v6.wiki/

**Comment by bahabryra** [comment]
ugg again srry for wasting your time it was on custom block list but i guess someone reported to lightspeed god dang it its so annoying but ik that as of right now .localplayer.dev is unblocked i hope werre faster this time lol






On Wednesday, December 25, 2024 at 10:30:02 AM CST, rednotsus ***@***.***> wrote: 







all good try http://docs.v6.wiki/

**Comment by RedNotSus** [comment]
https://v2202412248092306146.luckysrv.de/

**Comment by bahabryra** [comment]
IT WORKEEED ya could you delete this ASAP so lightspeed never finds out i cant rn
so like the issue will not exist anymore not even in the completed section :)






On Wednesday, December 25, 2024 at 08:33:01 PM CST, rednotsus ***@***.***> wrote: 







https://v2202412248092306146.luckysrv.de/
